name: Build RDBeD

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

permissions:
  contents: read

jobs:

  build:
    runs-on: windows-2022
    strategy:
      matrix:
        version: [2022]
        configuration: [Debug, Release]
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET command line
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: 8.x

      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore

      - name: Create Docker Image
        run: dotnet publish ./Wowshop.API/Wowshop.API.csproj /t:PublishContainer -r linux-x64

      - name: Get SHA
        id: slug
        shell: powershell
        run: echo "sha8=$('${{github.sha}}'.Substring(0,8))"  >> $env:GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          name: RDBeD-${{matrix.version}}-${{matrix.configuration}}-${{ steps.slug.outputs.sha8 }}
          path: ${{matrix.configuration}}/**/*

